version: '3.8'

services:
  frontend:
    build:
      context: ./path-to-angular-frontend
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./makerspace
    ports:
      - "7100:7100"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
